### ISSUE TITLE
Shell scripts and executables should use the same execution options

### ISSUE THREAD

**Issue by Spiros-N-Agathos** [nkallima/sim-universal-construction#21]
Currently the shell scripts i.e. `bench.sh` an `validate.sh` take the options in the form `-option=value`, in contrast the actual benchmark requires the options to be given as `-option value`.
This maybe confuse the user of the framework.

The goal is to use either option format uniformly throughout the Synch framework.

**Comment by nkallima** [comment]
@Spiros-N-Agathos

Done in v3.0.0-dev branch. v3.0.0 will be officially released very soon.
