### ISSUE TITLE
benchmarks emit "mbind: Function not implemented" in WSL2

### ISSUE THREAD

**Issue by Spiros-N-Agathos** [nkallima/sim-universal-construction#30]
Trying the tool in WSL2 debian 10 box (gcc  8.3.0) with single NUMA node the benchmarks emit warning:
"mbind: Function not implemented"

The solution is to deactivate the NUMA_SUPPORT compile flag.

It would be nice if the make system could auto-deactivate this setting.

**Comment by nkallima** [comment]
It seems that this is a warning message that the mbind system-call (possibly called by some function of libnuma) is not provided by the kernel.
Could you please provide:
1) version of the kernel,
2) architecture (is this a x86 machine?), and
3) and the status of kernel's NUMA flags (e.g., CONFIG_NUMA, CONFIG_NUMA_EMU, etc.). You could probably locate kernel's  configuration in /proc/config.gz

**Comment by Spiros-N-Agathos** [comment]
1. Linux DESKTOP-A0SSRMK 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
2. x86_64
3. # CONFIG_NUMA is not set, CONFIG_ARCH_SUPPORTS_NUMA_BALANCING=y

**Comment by nkallima** [comment]
It seems that the kernel is configured without NUMA support.
Thus, the warning shows that the memory allocation follows the fallback path.
