### ISSUE TITLE
[FEATURE] Add code coverage report in CI

### ISSUE THREAD

**Issue by williamfgc** [nkallima/sim-universal-construction#32]
**Is your feature request related to a problem? Please describe.**
Code coverage is desired to build confidence in the current CI test and to see how much is tested when users want to use a certain feature. It'd also help guidance when adding new tests.

**Describe the solution you'd like**
Either Codecov or Coveralls coverage report + a badge would be a great bonus.

**Describe alternatives you've considered**
None, but it should be a minor task

**Additional context**
Related to [JOSS review 3143](https://github.com/openjournals/joss-reviews/issues/3143)

**Comment by nkallima** [comment]
Thanks for your feedback!
Yes, I think it is a good idea to have a coverage report for the validation tests. I will check both Codecov and Coveralls in order to see which better suits the project.

BTW, in the v2.5.0 branch, I push all the improvements for the JOSS review. I will release it to the master branch whenever the desired changes/improvements are in a good shape.

**Comment by nkallima** [comment]
@williamfgc

I added a coverage report for validation checks to v2.5.0-dev branch (please check https://github.com/nkallima/sim-universal-construction/tree/v2.5.0-dev). It seems that the code-coverage is about 66% at this point.

**Comment by williamfgc** [comment]
@nkallima thanks, nice job. Just as a suggestion, automatic coverage report can be a badge in your ReadMe.md

**Comment by nkallima** [comment]
@williamfgc thanks for your comments and your reply. The badge is already there, in the README.md of v2.5.0-dev branch. In the v2.5.0 branch, I'm pushing all the improvements for the JOSS review. I will merge to the main branch whenever the desired changes/improvements are in a good shape.

**Comment by williamfgc** [comment]
@nkallima sounds great, thanks! Yes, I asked in #34 some docs on contributing to the code base. Typically, `master` or `main` has the latest tested code. Your call.

**Comment by nkallima** [comment]
@williamfgc, I replied for #34 in its own issue. Is it OK for you to close the current issue?

**Comment by williamfgc** [comment]
Sorry if I miss, if there a link to the report or steps to reproduce the coverage?

**Comment by nkallima** [comment]
@williamfgc, please check the report at https://app.codecov.io/gh/nkallima/sim-universal-construction (or simply you click at badge).
The coverage is calculated at each push request on v2.5.0-dev.

**Comment by williamfgc** [comment]
@nkallima look great! Thanks! Closing this.
