### ISSUE TITLE
[FEATURE] Improve Contributing documentation

### ISSUE THREAD

**Issue by williamfgc** [nkallima/sim-universal-construction#34]
**Is your feature request related to a problem? Please describe.**
Contributing is not clear for external engagement. 

**Describe the solution you'd like**
Clarify the desired workflow (fork-branch ? Should `master` (now `main` be up-to-date?).
It's not clear if someone would like to do a Pull Request where things should go.

**Describe alternatives you've considered**
Just expand Contributing.md

**Additional context**
Part of [JOSS review issue 3143](https://github.com/openjournals/joss-reviews/issues/3143)

**Comment by nkallima** [comment]
@williamfgc I will add some material. Thanks.

**Comment by nkallima** [comment]
@williamfgc 
I have added some new material in the Contributing documentation (see https://github.com/nkallima/sim-universal-construction/blob/v2.5.0-dev/CONTRIBUTING.md).

**Comment by williamfgc** [comment]
Thanks @nkallima looking good. Minor thing, please indicate in [this section](https://github.com/nkallima/sim-universal-construction/blob/v2.5.0-dev/CONTRIBUTING.md#ready-to-make-a-change) the target branch (is it `main`?) for the pull request. Otherwise, looks good.

**Comment by nkallima** [comment]
Thanks @williamfgc for your reply & your comments. I improved this point in the last commit (https://github.com/nkallima/sim-universal-construction/commit/50daa36ab51c0ecf2dfe29fc2fb8528652ade814).
In case you think that the Contributing file is in a good state, this issue could be closed.

> 
> 
> Thanks @nkallima looking good. Minor thing, please indicate in [this section](https://github.com/nkallima/sim-universal-construction/blob/v2.5.0-dev/CONTRIBUTING.md#ready-to-make-a-change) the target branch (is it `main`?) for the pull request. Otherwise, looks good.
