### ISSUE TITLE
[FEATURE] Switch master to main for default branch

### ISSUE THREAD

**Issue by williamfgc** [nkallima/sim-universal-construction#35]
**Is your feature request related to a problem? Please describe.**
GitHub has demoted the use of the `master` branch in favor of `main` going forward.  

**Describe the solution you'd like**
It should be an easy fix: https://github.com/github/renaming 

**Describe alternatives you've considered**
None

**Additional context**
[GitHub docs for changing default branch](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/changing-the-default-branch)
Part of [JOSS review issue 3143](https://github.com/openjournals/joss-reviews/issues/3143)

**Comment by nkallima** [comment]
@williamfgc thanks for pointing this out. I just fixed it and I'm closing this issue.
