### ISSUE TITLE
Enhancements on bench.sh

### ISSUE THREAD

**Issue by nkallima** [nkallima/sim-universal-construction#9]
It seems that the usability of bench.sh is somewhat restricted since v2.0.
More specifically, bench.sh passively passes the command-line arguments to the executed benchmark.
Some easy but useful enhancements could be the following:

1. Run the benchmark with different number 'n' of threads. 

- In case that a machine is equipped with 80 cores,  bench.sh runs the benchmark with n=1,10,20,...,80 threads (step is equal to 10 in this case). 
- In case that a machine is equipped with 64 cores,  bench.sh runs the benchmark with n=1,8,16,24,...,64 threads (step is equal to 8).
-  In cases that the number of cores is less or equal to 8, the step should be equal to 1.

2. The user should be able to define the step-size with an argument. 
3. The user should also be able to define a maximum number of threads, which may be greater or equal to the number of cores.

**Comment by Spiros-N-Agathos** [comment]
This means that by default the number of runs should be <=8?
